# Generated by Django 5.0.6 on 2024-05-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=100)),
                ('request_body', models.TextField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
