# Generated by Django 5.0.6 on 2024-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NMOS_Explorer_PoC', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
